# Generated by Django 5.2.8 on 2025-11-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'الملف الشخصي', 'verbose_name_plural': 'الملفات الشخصية'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
    ]
